
global:
  name: jinwyp


# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------

# EMBEDDED SERVER CONFIGURATION (ServerProperties)

server:
  port: 8090
  error:
    whitelabel:
      enabled: false



# LOGGING


# Log levels severity mapping. For instance `logging.level.org.springframework=DEBUG`
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
        aop:
          interceptor:
            JamonPerformanceMonitorInterceptor: TRACE
    com:
      example:
        demo: DEBUG



# SPRING MVC (WebMvcProperties)


# https://stackoverflow.com/questions/28902374/spring-boot-rest-service-exception-handling/30193013#30193013
# If a "NoHandlerFoundException" should be thrown if no Handler was found to process a request.


# SPRING RESOURCES HANDLING (ResourceProperties)
# Disable default resource handling. Not redirect to 404


spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  data:

    rest:
      base-path: api
      return-body-on-create: true
      return-body-on-update: true

    mongodb:
      database: springdb
      host: localhost
      port: 27017


# MONGODB (MongoProperties)



